### ISSUE TITLE
Use the iron-icon rtl mirroring

### ISSUE THREAD

**Issue by awikkerink** [Brightspace/d2l-icons-ui#82]
https://github.com/PolymerElements/iron-iconset-svg/pull/54

@dlockhart Did you know about this? It was merged 2 days ago.

**Comment by dlockhart** [comment]
Haha yeah I just saw it, I guess we're on the right track! Or we're being watched...

**Comment by awikkerink** [comment]
:suspect: :eyes:

**Comment by dbatiste** [comment]
`d2l-icons` have been updated to use.
