### ISSUE TITLE
Fix color transition on icon-button and icon-link

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-icons-ui#86]
The color transition for `d2l-icon-button` and `d2l-icon-link` on hover/focus isn't getting applied. Seems to be related to the transition CSS property being applied to something with the class `..d2l-icon-button-icon`, but [nothing has that class](https://github.com/Brightspace/d2l-icons-ui/blob/master/d2l-icon-button-shared-styles.html#L45).

**Comment by awikkerink** [comment]
Doh!
